# Tint16 generated palette
# Theme: "laubwald-spring"
# Author: "Itzalak"

[colors.primary]
# Default colors
background = "#152719"
foreground = "#ccedd1"

# Normal colors
[colors.normal]
black = "#224029"
red = "#e14433"
green = "#a2bc3c"
yellow = "#ec984d"
blue = "#3c8cbf"
magenta = "#bb9af6"
cyan = "#3b9586"
white = "#90c99b"

# Bright colors
[colors.bright]
black = "#3a6243"
red = "#f36552"
green = "#b7d348"
yellow = "#f7b37c"
blue = "#4fa1d7"
magenta = "#cdb6f9"
cyan = "#47ac9b"
white = "#e6f6e8"
