# Tint16 generated palette
# Theme: "laubwald-night"
# Author: "Itzalak"

[colors.primary]
# Default colors
background = "#060a07"
foreground = "#dce6dd"

# Normal colors
[colors.normal]
black = "#1d251e"
red = "#d65342"
green = "#43985a"
yellow = "#b9941a"
blue = "#2d8cc5"
magenta = "#985fe6"
cyan = "#2993a3"
white = "#abbfae"

# Bright colors
[colors.bright]
black = "#475749"
red = "#e96e5d"
green = "#4fb069"
yellow = "#d2a920"
blue = "#41a2df"
magenta = "#aa7cf1"
cyan = "#32aabc"
white = "#edf2ee"
