# Tint16 generated palette
# Theme: "laubwald-night"
# Author: "Itzalak"

[colors]
ansi = [
    '#1d251e',
    '#d65342',
    '#43985a',
    '#b9941a',
    '#2d8cc5',
    '#985fe6',
    '#2993a3',
    '#abbfae',
]
brights = [
    '#475749',
    '#e96e5d',
    '#4fb069',
    '#d2a920',
    '#41a2df',
    '#aa7cf1',
    '#32aabc',
    '#edf2ee',
]
cursor_border = '#edf2ee'
cursor_bg = '#1d251e'
cursor_fg = '#475749'
background = '#060a07'
foreground = '#dce6dd'
selection_bg = '#475749'
selection_fg = '#dce6dd'

[colors.indexed]

[metadata]
name = 'Wezterm'
